# Generated by Django 5.0.1 on 2024-02-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
