# Generated by Django 5.0.1 on 2024-02-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='car',
        ),
    ]
